### ISSUE TITLE
Can't use an undefined value as a HASH reference

### ISSUE THREAD

**Issue by vytas-dauksa** [mjemmeson/Test-MethodFixtures#1]
According to your documentation new doesn't require arguments passed in, but following

```
perl -MTest::MethodFixtures -E 'Test::MethodFixtures->new;'
```

generates
`Can't use an undefined value as a HASH reference at [..]/Test/MethodFixtures.pm line 35.` error.

**Comment by mjemmeson** [comment]
Thanks!
Fixed in v0.05
